### ISSUE TITLE
Proposal. Unified testing framework for ports

### ISSUE THREAD

**Issue by vityaman** [mike-lischke/antlr4-c3#172]
## Problem

Currently we need to translate unit tests for each port from the original TS library. It is a code duplication that makes it harder to maintain the project, because adding new test cases is harder -- need to "broadcast" a code to all ports, so actually port testsuites differs and therefore there is a risk of behavior divergence.

## Proposal

I propose to develop a unified testing framework like in the `ANTLR4`. Tests can be described in a human-readable format (for example, YAML) and stored in a separate directory. To run tests each port should provide a test driver, like in `ANTLR4` project. Thanks to LLM existence porting a test driver should be quite easy.

Also the `TypeScript` library can be moved to `ports` section. It will make it easier to work with a project in an IDE -- just open directory `port/X`. And also it is like in `ANTLR4`, so more comfortable for users.

### Project Structure

So the project directory could look like 
```
.github/workflows
 \_ csharp.yml
 |_ cpp.yml
 |_ java.yml
 |_ typescript.yml
port
 \_ csharp
 |_ cpp
 |_ java
 |_ typescript # still contain additional features and unit tests
test
 \_ golden
   \_ whitebox
     \_ 001.yml
     |_ 002.yml
     |_ Whitebox.g4
   \_ expression
     \_ 001.yml
     |_ 002.yml
     |_ Expression.g4
 \_ golden.py
doc/image
 \_ token-position.png
LICENSE.txt
README.md
```

### Golden Test Format

```
name: "Caret at transition to rule with non-exhaustive follow set (optional tokens)"
excludes: [ csharp, java ] # when behavior is diverged or a major update is in progress
input: 
  text: "LOREM |" # instead of caretTokenIndex
  rule: "test1"   # optional
output:
  tokens:
    count: 5         # optional, when undefined `contain` means exactly contain
    contain:
    - [IPSUM, DOLOR] # when following is not empty
    - [DOLOR]        # can be converted to and from ruleIndex via vocabulary
    - [SIT]
    - [AMET]
    - [CONSECTETUR]
  rules:
    count: 5
    contain:
    - root: "functionRef" # can be converted to and from ruleIndex via Parser
      stack: [ ... ]
      start: 6
```
